
version: '3.8'
services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
