
version: '3.8'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    command: --secure-file-priv=""
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
  
  r:
    build:
      context: .
      dockerfile: r/Dockerfile.r
    container_name: r_script_runner
    depends_on:
      mysql:
        condition: service_healthy
      
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mydb
    command: Rscript /app/r-scripts/test.R

volumes:
  mysql-data:
