services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    command: --secure-file-priv=""
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
  r:
    build:
      context: .
      dockerfile: r/Dockerfile.r
    container_name: r_script_runner
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mydb
    command: Rscript /app/r-scripts/test.R
  r-health:
    build:
      context: .
      dockerfile: r/Dockerfile.r
    command: Rscript /app/r-scripts/r-health.R
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "8000:8000"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      r-health:
        condition: service_healthy
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
volumes:
  mysql-data:
