
version: '3.8'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    command: --secure-file-priv=""
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  r:
    build:
      context: .
      dockerfile: Dockerfile.r
    container_name: r_script_runner
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mydb
    command: Rscript /app/r-scripts/test.R

volumes:
  mysql-data:
