name: R CI Pipeline

on:
  push:
    paths:
      - 'r-scripts/*.R'
      - 'r/Dockerfile.r'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'r-scripts/*.R'
      - 'r/Dockerfile.r'

jobs:
  r-lint-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install lintr
        run: Rscript -e 'install.packages("lintr", repos="https://cloud.r-project.org")'

      - name: Run lintr
        run: Rscript -e 'lintr::lint_dir("r-scripts")'

      - name: Build R Docker image
        run: docker build -t big-data-app -f r/Dockerfile.r .

      # Optional: Push to Docker Hub
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Push image to Docker Hub
      #   run: docker tag big-data-r your_dockerhub_user/big-data-r:latest && docker push your_dockerhub_user/big-data-r:latest
